#	$Id: Makefile,v 1.1 2009/05/22 13:02:20 ohauer Exp ohauer $

PROG=	reorg_spamdb
SRCS=	reorg_spamdb.c
MAN=	reorg_spamdb.8

CFLAGS+= -Wall -Wstrict-prototypes -I${.CURDIR}/../spamd
#.PATH:  ${.CURDIR}/../spamd

.include <bsd.prog.mk>
